language: python
os:
  - linux
#  - osx
python:
  - '2.7'
  - '3.6'

git:
  depth: 1
cache: pip
install:
  - pip install -r requirements.txt

# NO NEED FOR ENV, THE ENTIRE BUILDING WILL STOP IF 'SCRIPT' FAILS
script:
  - py.test -v --cov-report=xml --cov=kinoko tests

before_deploy:
  - codecov --token=6cd07a53-f1bf-4929-83ae-6d394c0802d1
  - openssl aes-256-cbc -K $encrypted_5cad0a958d01_key -iv $encrypted_5cad0a958d01_iv -in .pypirc.enc -out ~/.pypirc -d
deploy:
  provider: script
  skip_cleanup: true
  on:
    python: '2.7' # avoid uploading from multiple versions, conflict
    branch:
      - master
      - release
  script: python setup.py bdist_wheel upload -r pypi
