language: python
os:
  - linux
#  - osx
python:
  - '2.7'
  - '3.6'

git:
  depth: 1
cache: pip
install:
  - pip install -r requirements.txt

# NO NEED FOR ENV, THE ENTIRE BUILDING WILL STOP IF 'SCRIPT' FAILS
script:
  - py.test

before_deploy:
  - codecov
  - openssl aes-256-cbc -K $encrypted_15a04db7c7ae_key -iv $encrypted_15a04db7c7ae_iv -in .pypirc.enc -out ~/.pypirc -d
deploy:
  provider: script
  skip_cleanup: true
  on:
    python: '2.7' # avoid uploading from multiple versions, conflict
    branch:
      - master
      - release
  script: python setup.py bdist_wheel upload -r pypi
