site_name: Kinoko
site_description: Detailed Documentation for Kinoko
site_author: Weishuo QIAN

repo_url: https://github.com/koyo922/kinoko
edit_uri: https://github.com/koyo922/kinoko/edit/master/docs

theme:
  name: 'material'

plugins:
  - search

extra:
  search:
    language: 'en, ja'
  social:
    - type: 'weixin'
      link: './assets/images/wechat_koyo922.jpg'
    - type: 'github'
      link: 'https://github.com/koyo922'
    - type: 'linkedin'
      link: 'https://linkedin.com/in/weishuo-qian-524264119'

extra_javascript:
  - https://cdn.bootcss.com/mathjax/2.7.5/latest.js?config=TeX-AMS-MML_HTMLorMML
  - ./assets/js/mathjax-config.js

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: true
      linenums: true
  - meta
  - toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.extra
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist
  - pymdownx.tilde

pages:
  - Home: index.md
  - Get Started: start.md
  - Format Specimen: format_specimen.md
  - Release Notes: changelog.md
