site_name: Kinoko for Text
site_description: Detailed Documentation for Kinoko
site_author: Weishuo QIAN

repo_url: https://github.com/koyo922/kinoko
edit_uri: https://github.com/koyo922/kinoko/edit/master/docs

theme:
  name: 'material'

plugins:
  - search
  - minify:
      minify_html: true

extra:
  search:
    language: 'en, ja'
  social:
    - type: 'weixin'
      link: '/assets/images/wechat_koyo922.jpg'
    - type: 'github'
      link: 'https://github.com/koyo922'
    - type: 'linkedin'
      link: 'https://linkedin.com/in/weishuo-qian-524264119'

extra_javascript:
  - https://cdn.bootcss.com/mathjax/2.7.5/latest.js?config=TeX-AMS-MML_HTMLorMML
  - ./assets/js/mathjax-config.js

markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.codehilite:
      guess_lang: false
      linenums: true
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.extra
  - pymdownx.highlight

nav:
  - Kinoko: index.md
  - Get Started: getting-started.md
  - Text Processing:
    - csv: csv.md
    - logging: log.md
  - Network: network.md
  - Bash Utils: bash.md
  - Functional Utils: func.md
  - Visual Utils: visual.md
  - Time Series Analysis Tool: time_series.md
  - Release Notes: changelog.md
  - Format Specimen: format_specimen.md
